[package]
name = "documuncher"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
data = { path = "../data" }
salvo = "*"
tokio = { version = "1", features = ["macros", "parking_lot"] }
